-- Datos de compra importados desde lista_compra.json
-- Ejecutar después de 002_datos_dieta.sql

insert into public.shopping_items (name, quantity, category, item_order) values
  ('Pollo', '1.3-1.5 kg', 'Proteínas', 1),
  ('Ternera Magra O Carne Picada', '1 kg', 'Proteínas', 2),
  ('Pavo Loncheado', '400 g', 'Proteínas', 3),
  ('Salmon', '350 g', 'Proteínas', 4),
  ('Merluza', '400 g', 'Proteínas', 5),
  ('Huevos', '24-30 unidades', 'Proteínas', 6),
  ('Lentejas Secas', '150-200 g', 'Proteínas', 7),
  ('Pasta', '600 g', 'Cereales y carbohidratos', 1),
  ('Arroz', '500 g', 'Cereales y carbohidratos', 2),
  ('Avena', '400 g', 'Cereales y carbohidratos', 3),
  ('Pan Integral', '1-1.5 kg', 'Cereales y carbohidratos', 4),
  ('Tortillas De Trigo O Maiz', '1 paquete', 'Cereales y carbohidratos', 5),
  ('Patatas', '2.5-3 kg', 'Cereales y carbohidratos', 6),
  ('Cereales Tipo Corn Flakes', '1 paquete', 'Cereales y carbohidratos', 7),
  ('Pan De Hamburguesa', '1 paquete', 'Cereales y carbohidratos', 8),
  ('Yogur Natural O Alto En Proteina', 'aprox. 2 kg', 'Lácteos y alternativas', 1),
  ('Yogur Vegetal Rico En Proteina', 'cantidad necesaria para Persona 1', 'Lácteos y alternativas', 2),
  ('Leche', '1-2 litros', 'Lácteos y alternativas', 3),
  ('Queso Fresco', '400 g', 'Lácteos y alternativas', 4),
  ('Mozzarella', '1-2 bolas', 'Lácteos y alternativas', 5),
  ('Parmesano', '1 pieza o paquete pequeño', 'Lácteos y alternativas', 6),
  ('Queso Para Tacos Y Hamburguesas', '1 paquete', 'Lácteos y alternativas', 7),
  ('Platanos', '1.5-2 kg', 'Frutas', 1),
  ('Manzanas', '4-6 unidades', 'Frutas', 2),
  ('Kiwis', '4-6 unidades', 'Frutas', 3),
  ('Frutos Rojos', '300-400 g', 'Frutas', 4),
  ('Naranjas O Mandarinas', '4-6 unidades', 'Frutas', 5),
  ('Fruta Variada', '1-2 kg adicionales, al gusto', 'Frutas', 6),
  ('Tomates', '1-1.5 kg', 'Verduras', 1),
  ('Tomates Cherry', '400 g', 'Verduras', 2),
  ('Calabacines', '1-1.5 kg', 'Verduras', 3),
  ('Zanahorias', '500-750 g', 'Verduras', 4),
  ('Pimientos', '750 g-1 kg', 'Verduras', 5),
  ('Lechuga O Mezcla De Ensalada', '2-3 bolsas o equivalente', 'Verduras', 6),
  ('Brocoli', '1-2 unidades', 'Verduras', 7),
  ('Judias Verdes', '500 g', 'Verduras', 8),
  ('Espinacas', '300-400 g', 'Verduras', 9),
  ('Aceite De Oliva Virgen Extra', '1 botella', 'Grasas y condimentos', 1),
  ('Aguacates', '3-4 unidades', 'Grasas y condimentos', 2),
  ('Nueces O Frutos Secos', '250-300 g', 'Grasas y condimentos', 3),
  ('Crema De Cacahuete', '1 bote', 'Grasas y condimentos', 4),
  ('Pesto', '1 bote pequeño', 'Grasas y condimentos', 5),
  ('Miel', '1 bote pequeño', 'Grasas y condimentos', 6),
  ('Proteina En Polvo', 'opcional', 'Otros', 1),
  ('Cafe', 'segun consumo habitual', 'Otros', 2),
  ('Salsa De Yogur', '1 bote pequeño o ingredientes para prepararla', 'Otros', 3),
  ('Especias', 'al gusto', 'Otros', 4)
;

-- Resumen: 47 productos de compra